Requested matches can be played on non-trusted clients
aiarena/aiarena-web pull request #385
Opened 2022-03-20 16:09 UTC by ratosh

2022-03-21 23:07 UTC, ratosh commented
Working now

2022-04-02 14:29 UTC, lladdy commented on aiarena/core/management/commands/seed.py
> +
Any specific reason for this change?
I believe it's functionally identical to how it was.

2022-04-02 14:30 UTC, lladdy commented on aiarena/core/management/commands/seed.py
> -        client.set_api_token(api_token)
This having been removed could potentially be why the seed test is failing.

2022-04-02 14:35 UTC, lladdy commented on aiarena/core/tests/testing_utils.py
> +        response = self.django_client.post(url)
You've removed the setting of the headers here.
Was this intentional?

2022-04-02 14:43 UTC, ratosh commented on aiarena/core/management/commands/seed.py
> +
Change was part of my try to fix seed testing. I'll revert.

2022-04-02 14:45 UTC, ratosh commented on aiarena/core/tests/testing_utils.py
> +        response = self.django_client.post(url)
Yes

2022-04-02 15:14 UTC, ratosh commented on aiarena/core/management/commands/seed.py
> -        client.set_api_token(api_token)
Arena client communication is on a different instance. Will change the new client to behave like the old part using api_token headers only.

2022-05-09 09:11 UTC, lladdy requested changes
@ratosh Apologies for the delay in getting around to re-addressing this PR.
 
I'd like to separate out the changes that aren't specifically relevant to requested matches being played by non-trusted clients.
Can you please extract such changes into separate PRs to this one?
Try to minimize non-relevant changes to the existing code in this PR (such as formatting).
This will make it much easier to spot any issues.

I can optionally do it if you'd prefer/don't have time at the moment.

Some quick ones I have identified.
- VS Code related change
- The deletion of exampe-dev-env.py
- Changes to settings.py file
- Docker changes
- Restructure of test code

If some of these things are desirable to keep in this PR, first extract/PR them and I'll merge to staging so the diff between this branch and staging is much simpler.

2022-08-01 02:38 UTC, lladdy commented
Closing - PR recreated here: https://github.com/aiarena/aiarena-web/pull/427

2022-08-01 02:38 UTC, closed without merging