Update README.md
aiarena/aiarena-web pull request #94
Opened 2020-11-04 07:06 UTC by 0701pawan

2020-11-04 10:49 UTC, lladdy requested changes
Hi @0701pawan,
Thanks for your contribution! :)
I have submitted some change requests for you to review.
Let me know if you have any thoughts.

2020-11-04 10:49 UTC, lladdy commented on README.md
> +Django template is used for website frontend
```suggestion
Django templates are used for the website frontend
```

2020-11-04 10:49 UTC, lladdy commented on README.md
> +This is an amazing website which gives you the sense of thrill unables you to compete with other bots across the world
```suggestion
This is an amazing website which gives you a sense of thrill and enables you to compete with other bots across the world 
```

2020-11-04 14:36 UTC, 0701pawan commented
Thank you 
I think adding pictures to the readme would make it more beautiful.

2020-11-04 19:01 UTC, lladdy commented
> 
> 
> Thank you
> I think adding pictures to the readme would make it more beautiful.

@0701pawan 
I very much agree. Do you have any suggestions for pictures we might add?

2020-11-05 05:49 UTC, 0701pawan commented
I think screenshots from the website would work

2020-11-05 06:15 UTC, 0701pawan commented
I have added some images  please have a look

2020-11-06 07:38 UTC, 0701pawan commented
Just a gentle reminder I  added some images in the readme have a look

2020-11-06 15:51 UTC, eladyaniv01 commented
> Just a gentle reminder I added some images in the readme have a look

Thank you so much for your work @0701pawan,
We are aware of it and appreciate it dearly,  please be patient while we find the time to review it properly.

2020-11-06 16:57 UTC, 0701pawan commented
thankyou

2020-11-12 13:27 UTC, lladdy commented
Hi @0701pawan,
You'll need to review what the changes look like.
There are two images separated by a white line and they have watermarks from an un-activated windows on them.

2021-06-14 13:17 UTC, danielvschoor commented
Closing due to no activity in more than 6 months

2021-06-14 13:17 UTC, closed without merging